# Generated by Django 5.0.1 on 2024-01-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntuaflixEpa_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nameobject',
            name='birthYear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nameobject',
            name='primaryProfession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
