# Generated by Django 5.0.1 on 2024-01-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TitleBasic',
            fields=[
                ('tconst', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('titleType', models.CharField(blank=True, max_length=255, null=True)),
                ('primaryTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('originalTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('isAdult', models.IntegerField(blank=True, null=True)),
                ('startYear', models.IntegerField(blank=True, null=True)),
                ('endYear', models.IntegerField(blank=True, null=True)),
                ('runtimeMinutes', models.IntegerField(blank=True, null=True)),
                ('genres', models.CharField(blank=True, max_length=255, null=True)),
                ('img_url_asset', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
